spring.application.name=cursos-api
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/cursos
spring.datasource.username=cursos
spring.datasource.password=cursos
spring.jpa.hibernate.ddl-auto=update
