spring.application.name=cursos-api
server.port=8080
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cursos}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cursos}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cursos}
spring.jpa.hibernate.ddl-auto=update
